Update processing algorithms
GispoCoding/eis_qgis_plugin pull request #39
Opened 2023-11-27 07:26 UTC by Mtk112

Added missing algorithms.
Split PCA into vector and raster.
Modified project structure.

2023-11-27 11:03 UTC, nmaarnio requested changes

2023-11-27 11:03 UTC, nmaarnio commented on eis_qgis_plugin/processing/algorithms/validation/plot_correlation_matrix.py
> +        )
I'm not 100% sure, but I think this function is used for vector data, so you could change the input to that (this function call would actually both produce the correlation matrix and then plot it).

2023-11-27 11:03 UTC, nmaarnio commented on eis_qgis_plugin/processing/algorithms/vector_processing/cell_based_association.py
> +        )
According to Toolkit, there could be multiple vector inputs.

2023-11-27 11:03 UTC, nmaarnio commented on eis_qgis_plugin/processing/algorithms/vector_processing/cell_based_association.py
This is quite complicated to implement with the input definitions of Toolkit... Maybe just leave it as draft for now, and let's take a look at it later? So you could comment everything out in the file and leave it like that

2023-11-28 05:32 UTC, Mtk112 commented on eis_qgis_plugin/processing/algorithms/exploratory_analysis/feature_importance.py
> +        )
Changed these to QgsProcessingParameterRasterLayer, double checked that x_test on toolkit expects a single np.ndarray. Also, I moved this to drafts, more about drafts further down the comments.

2023-11-28 05:39 UTC, Mtk112 commented on eis_qgis_plugin/processing/algorithms/exploratory_analysis/statistical_tests.py
My mistake, added all the functions as separate algorithms.

2023-11-28 05:45 UTC, Mtk112 commented on eis_qgis_plugin/processing/algorithms/transformations/one_hot_encoding.py
> +        )
Changed parameter type to Field. I added clarification to the description.

2023-11-28 05:55 UTC, Mtk112 commented on eis_qgis_plugin/processing/algorithms/vector_processing/cell_based_association.py
I created a new drafts directory under algorithms, as just commenting out the files causes issues with building the plugin. I moved CBA and Feature importance under the drafts directory to mark them as work in progress.

2023-11-28 09:36 UTC, merged